name:
  RNAdist
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - python >=3.6
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - networkx
  - biopython
  - pandas
  - smac >=1.4
  - plotly
  - dash >=2.5
  - dash-bootstrap-components
  - viennarna >=2.4
  - pybind11