name:
  RNAdist
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda =11.6
  - smac >=1.4
  - pyg
  - viennarna
  - networkx
  - biopython
  - pandas
  - plotly
  - dash >=2.5
  - dash-bootstrap-components
  - pybind11
  - cython
  - python >=3.8
  - pip
  - versioneer