name: Build RNAdist Docker image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Matches version tags like v0.3.1
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/rnadist:${{ startsWith(github.ref, 'refs/tags/') && 'latest' || 'nightly' }}
            ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('{0}/rnadist:nightly-{1}', secrets.DOCKERHUB_USERNAME, github.sha) }}
