
on:
  pull_request:
    branches:
      - main

jobs:
  test-package:
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge,defaults,bioconda
          auto-activate-base: false
          activate-environment: RNAdistEnv
          environment-file: environment.yml

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          eval "$(conda shell.bash hook)"
          conda activate RNAdistEnv
          pip install ./ --no-deps --no-build-isolation
          pip install pytest

      - name: test package
        run: |
          pytest --pyargs RNAdist
